apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-template.fullname" . }}-spring-mysql-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Cardholder DB
  CARDHOLDER_ADMIN_USER: {{ .Values.mysql.cardholderdb.adminUser | quote }}
  CARDHOLDER_ADMIN_PASSWORD: {{ .Values.mysql.cardholderdb.adminPassword | quote }}
  CARDHOLDER_USER: {{ .Values.mysql.cardholderdb.user | quote }}
  CARDHOLDER_USER_PASSWORD: {{ .Values.mysql.cardholderdb.userPassword | quote }}

  # Card DB
  CARD_ADMIN_USER: {{ .Values.mysql.carddb.adminUser | quote }}
  CARD_ADMIN_PASSWORD: {{ .Values.mysql.carddb.adminPassword | quote }}
  CARD_USER: {{ .Values.mysql.carddb.user | quote }}
  CARD_USER_PASSWORD: {{ .Values.mysql.carddb.userPassword | quote }}

  # PAN DB
  PAN_ADMIN_USER: {{ .Values.mysql.pandb.adminUser | quote }}
  PAN_ADMIN_PASSWORD: {{ .Values.mysql.pandb.adminPassword | quote }}
  PAN_USER: {{ .Values.mysql.pandb.user | quote }}
  PAN_USER_PASSWORD: {{ .Values.mysql.pandb.userPassword | quote }}